/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chitchat;

import static chitchat.NewJFrame.ip;
import static chitchat.un.in;
import static chitchat.un.out;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import static java.lang.System.exit;
import java.net.Socket;
import static java.time.Clock.system;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Joytu
 */
public class game extends javax.swing.JFrame {

    /**
     * Creates new form game
     */
    protected static  DataInputStream in;
    protected static Socket so;
    String number;
    String guess;
    protected static DataOutputStream out;
    boolean af;
    boolean bl;
    boolean loop;
    public game()
    {
        initComponents();
    }
    public game(Socket s) {
        initComponents();
       so=s;
            innitialize();
      
        
        System.out.println(so);
        chathandle2 ch= new chathandle2();
        ch.start();
        
    }
    public void innitialize() 
    {
        try{
        in = new DataInputStream(so.getInputStream());
        out= new DataOutputStream(so.getOutputStream());
       af=true;
       bl=true;
       loop=true;
        
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
  
    public void answer(int x)
    {
        int i=0;
        JDialog dialog=null;
        System.out.println("inside answer method");
        while(i<3){
        
       // if(x!=9999){
        //    dialog.dispose();
        guess=JOptionPane.showInputDialog("Guess the number");
        int result = Integer.parseInt(guess);
        if(result>x)
        {
            JOptionPane.showMessageDialog(null,"Thing a lower number");
            i++;
        }
        else if(result<x)
        {
            JOptionPane.showMessageDialog(null,"Think a higher number");
            i++;
        }
        else if(result==x)
        {
            JOptionPane.showMessageDialog(null,"CONGRATULATION YOU WON!!!!!!! ");
                try {
                    out.writeUTF("888");
                } catch (IOException ex) {
                    Logger.getLogger(game.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.dispose();
                bl=false;
                loop=false;
                
                break;
        }
            
       
        }
        if(bl==true){
        JOptionPane.showMessageDialog(null,"You failed to guess the number");
        
        try {
            out.writeUTF(";;;");
        } catch (IOException ex) {
            Logger.getLogger(game.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        loop=false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lb = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chitchat/rsz_1317414.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 105, 84, -1));

        lb.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        lb.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 294, 342, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chitchat/rsz_images.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 105, 81, 89));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chitchat/3574b2a5-e223-40a7-8240-a4da13b6fc18_main.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static boolean isNumeric(String strNum) {
    try {
        double d = Double.parseDouble(strNum);
    } catch (NumberFormatException | NullPointerException nfe) {
        return false;
    }
    return true;
}
    public void destroys()
    {
        this.dispose();
        //exit(0);
        //game gm= new game();
       
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      boolean op=true;
        if(af==true){
        try {
            // TODO add your handling code here:
            System.out.println("working before");
             out.writeUTF("000000");
             System.out.println("working afer");
            while(2>1){
           
            String gs;
            //if(op==true){
            gs=JOptionPane.showInputDialog("Give a number 1 - 100");
         //   }
            boolean t=isNumeric(gs);
            
            
            if(t==false)
            {
                JOptionPane.showMessageDialog(null,"please enter a number");
            }
            if(t== true)
            {
                int nu;
                nu=Integer.parseInt(gs);
                if(nu>=0&&nu<=100)
                {
                    out.writeUTF(gs);
                    System.out.println("gone");
                    lb.setText("wait for your friend answer");
                    break;
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"please enter a number from 1-100");
                }
            }
            }
        } catch (Exception ex) {
           // Logger.getLogger(game.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            out.writeUTF("]]]]");
        } catch (Exception ex) {
            Logger.getLogger(game.class.getName()).log(Level.SEVERE, null, ex);
        }
       this.dispose();
       loop=false;
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb;
    // End of variables declaration//GEN-END:variables
public class chathandle2 extends Thread{
    
    public void run()
    {
       while(2>1&&loop==true)
       {
           try {
               String nu;
               number= in.readUTF();
               System.out.println("inside loop");
               System.out.println("..............................................");
               if(number.equals("000000"))
               {
                   lb.setText("your friend want to give a number to guess!!!");
                   af=false;
               }
               else if(number.equals("888"))
               {
                    JOptionPane.showMessageDialog(null,"Your Friend Guess the right number");
                   destroys();
                   break;
                    
               }
               else if(number.equals(";;;"))
               {
                   JOptionPane.showMessageDialog(null,"you won!!!! your friend could not guess the correct number");
                   destroys();
                   break;
                  
               }
               else if(number.equals("]]]]"))
               {
                   JOptionPane.showMessageDialog(null,"Your friend exit from the game");
                   destroys();
                   break;
                   
               }
               else 
               {
                   nu=number;
               int result = Integer.parseInt(nu);
                   System.out.println(number);
               answer(result);
               }
           } catch (Exception ex) {
               
           }
       }
        
    }
}
}
