package chitchat;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dx
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    static public DataInputStream in;
   static public DataOutputStream out;
   String sendfile;
   String recive;
    static public InputStream is;
    static int flage=0;
    static OutputStream os;
    static Socket soc=null;
    static Socket soc2=null;
    static Socket soc3=null;
    static String dmsg;
    static String ip=null;
    String name;
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        popupMenu3 = new java.awt.PopupMenu();
        popupMenu4 = new java.awt.PopupMenu();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        phnno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lb = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        iptx = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        popupMenu3.setLabel("popupMenu3");

        popupMenu4.setLabel("popupMenu4");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 173, 124));
        jLabel1.setText("Phone no");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 120, 33));
        getContentPane().add(phnno, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 76, 253, 33));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 173, 124));
        jLabel2.setText("password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 116, 30));
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 127, 253, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chitchat/rsz_login-rounded-right.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 60, 50));

        lb.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 357, 22, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chitchat/rsz_13732.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 60, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chitchat/1554112_-_Copy_60x80 - Copy.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 319, 67, 80));

        iptx.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        iptx.setForeground(new java.awt.Color(255, 204, 204));
        getContentPane().add(iptx, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 310, 247, 89));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chitchat/rsz_1facebook-messenger-icon-transparent-background-javascript.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String url="jdbc:mysql://127.0.0.1/detail";
        String user="root";
        String pa="";
        boolean f;
         try{      
        Class.forName("com.mysql.jdbc.Driver");
       Connection connection =(Connection) DriverManager.getConnection(url,user,pa);
        Statement statement = connection.createStatement();
        ResultSet result;
        ResultSet result2;
        String nameck=phnno.getText(),passck=pass.getText();
       // if()
        //String query="SELECT password FROM info where phonno= "+nameck;//+" AND password= "+passck;
        String query="SELECT * FROM info where phonno="+nameck;//+passck;
       // result=statement.executeQuery(query);
       result=statement.executeQuery(query);
        //result.next();
       result.next();
        name=result.getString("name");
       if(result.getString("password").equals(passck)){
            System.out.println(result.getString("password"));
           connection.close();
            statement.close();
            while(true){
                  ip=JOptionPane.showInputDialog("your friend's ip addres?");
                  if(ip.length()<=0)
                  {
                      JOptionPane.showMessageDialog(null,"Can't be blank. you wont be able to connect");
                      System.out.println(ip+"dsdsa");
                  }
            if(ip.length()>0){
                System.out.println(ip);
        dmsg="Waiting for connection........";
        String[] options = {"Host","Connect"};
        int x=JOptionPane.showOptionDialog(null, "HOST OR CLIENT",
                "Click a button",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
        
       
                  
        System.out.println(x);
        if(x==0)
        {
            lb.setText("wait for connection");
            connection();
             break;
        }
        if(x==1)
        {
            lb.setText("wait for connection");
            connection1();
            break;
            
        }
                  }
           }
       
        if(soc!=null){
        un u= new un(soc,soc2,soc3,name);
        u.setVisible(true);
        this.dispose();
        }
       }    
       
       else
       {
           JOptionPane.showMessageDialog(null,"invalid data");
       }
       
        }catch(Exception e)
         {
             //System.out.println(e);
             JOptionPane.showMessageDialog(null,"invalid data");
         }
         
        //......................................................
        //......................................................
        //.......................................................
        //..........................................................
     /*   ip=JOptionPane.showInputDialog("your friend's ip addres?");
        dmsg="Waiting for connection........";
        String[] options = {"Host","Connect"};
        int x=JOptionPane.showOptionDialog(null, "Returns the position of your choice on the array",
                "Click a button",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
        
       
        
        System.out.println(x);
        if(x==0)
        {
            lb.setText("wait for connection");
            connection();
             
        }
        if(x==1)
        {
            lb.setText("wait for connection");
            connection1();
            
        }
        if(soc!=null){
        un u= new un(soc,soc2);
        u.setVisible(true);
        this.dispose();
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        account ac= new account();
        ac.setVisible(true);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
        InetAddress myIP=InetAddress.getLocalHost();
        iptx.setText(myIP.getHostAddress());
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
        
        
         
        
         
    }
   void  connection()
    {
        ServerSocket ss = null ;
        ServerSocket ss2=null;
        ServerSocket ss3=null;
        try {
            ss = new ServerSocket(9999);
            ss2= new ServerSocket(9998);
            ss3=new ServerSocket(9997);
            soc=ss.accept();
            soc2=ss2.accept();
            soc3=ss3.accept();
            dmsg="Connected succesfully ";
            //in = new DataInputStream(soc.getInputStream());
      //  out= new DataOutputStream(soc.getOutputStream());
        // is= soc.getInputStream();
        // os = soc.getOutputStream();
        }
    catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   static void  connection1()
    {
       // ServerSocket ss = null ;
        //Socket soc=null;
        while(soc==null){
        try {
            //ss = new ServerSocket(9999);
            //soc=ss.accept();
            
            soc=new Socket(ip,9999);
            soc2=new Socket(ip,9998);
            soc3=new Socket(ip,9997);
            dmsg="connected";
            in = new DataInputStream(soc.getInputStream());
        out= new DataOutputStream(soc.getOutputStream());
         is= soc.getInputStream();
         flage=1;
            //System.out.println("dhoom");
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      //  return soc;
    }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iptx;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lb;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField phnno;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private java.awt.PopupMenu popupMenu3;
    private java.awt.PopupMenu popupMenu4;
    // End of variables declaration//GEN-END:variables

}

